# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_url', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ename', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_desc', models.TextField(blank=True, null=True)),
                ('infos', models.CharField(blank=True, max_length=255, null=True)),
                ('celebritys', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('req_url', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_type', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_area', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_minutes', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_year', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_time', models.CharField(blank=True, max_length=255, null=True)),
                ('player_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
